### ISSUE TITLE
.pgbomit ignored on zip file

### ISSUE THREAD

**Issue by mzanatta** [phonegap/build#473]
First, sorry for my english.

Since two days ago, when i use phonegap build, the file .pgbomit is ignored when i upload a zip file.

The apk generated have the res folder in assets when it should be ignored.

App ID: 1669797

I attached a few pictures so you can see the structure of the zip file.

![image1](https://cloud.githubusercontent.com/assets/12038460/10635407/e9a830f6-77ce-11e5-80bd-d9f29573600b.png)
![image2](https://cloud.githubusercontent.com/assets/12038460/10635408/e9cd3612-77ce-11e5-9be9-8160b4eadcc7.png)

**Comment by bau720123** [comment]
hi @mzanatta 
I post a same problem just like yours
http://community.phonegap.com/nitobi/topics/-pgbomit-is-not-working-in-gradle-build
maybe you can post it too and join us

**Comment by goya** [comment]
fixed. sorry for the inconvenience.

**Comment by mzanatta** [comment]
Problem solved. Thanks

**Comment by bau720123** [comment]
thanks @goya 
solved

**Comment by rahulbhanushali** [comment]
I am still facing this issue.
Can someone please help in solving this?

**Comment by wildabeast** [comment]
@rahulbhanushali What's your App ID?
