### ISSUE TITLE
target-device handset in config.xml

### ISSUE THREAD

**Issue by deepslux** [phonegap/build#504]
Hi,

I would like to check if there is something wrong with my config.xml. The objective is to build ios app for iPhone only (not for iPad). I tried the recommended setting in config.xml, which is 
`<preference name="target-device" value="handset" />`.

However, iTunes Connect raises an error of "Your binary indicates support for iPad. You must provide an iPad screenshot."

config.xml setting is as follows:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<widget id="sg.tutella" version="16.03.03" versionCode="160303" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <name>Tutella</name>
  <description>
        Find the right tutor for your kid.
    </description>
  <author email="hello@tutella.sg" href="http://www.tutella.sg/">
      Tutella
    </author>
  <content src="index.html"/>
  <access origin="http://www.tutella.sg"/>
  <preference name="target-device" value="handset" />
  <preference name="orientation" value="default" />
  <preference name="fullscreen" value="false" />
  <preference name="webviewbounce" value="false"/>
  <preference name="UIWebViewBounce" value="false"/>
  <preference name="DisallowOverscroll" value="true"/>
  <preference name="android-minSdkVersion" value="16"/>
  <preference name="BackupWebStorage" value="none"/>
  <preference name="android-build-tool" value="gradle" />
  <preference name="phonegap-version" value="cli-6.0.0" />
  <feature name="StatusBar">
    <param name="ios-package" value="CDVStatusBar" onload="true"/>
  </feature>
  <plugin name="phonegap-plugin-push" spec="1.5.3" source="npm" />
  <plugin name="ionic-plugin-keyboard" spec="1.0.8" source="npm" />
  <plugin name="cordova-plugin-camera" spec="2.1.0" source="npm" />
  <plugin name="cordova-plugin-device" spec="1.1.1" source="npm" />
  <plugin name="cordova-plugin-vibration" spec="2.1.0" source="npm" />
  <plugin name="cordova-plugin-whitelist" spec="1.2.1" source="npm" />
  <platform name="ios">
    <icon src="resources/ios/icon/icon-40.png" width="40" height="40"/>
    <icon src="resources/ios/icon/icon-40@2x.png" width="80" height="80"/>
    <icon src="resources/ios/icon/icon-50.png" width="50" height="50"/>
    <icon src="resources/ios/icon/icon-50@2x.png" width="100" height="100"/>
    <icon src="resources/ios/icon/icon-60.png" width="60" height="60"/>
    <icon src="resources/ios/icon/icon-60@2x.png" width="120" height="120"/>
    <icon src="resources/ios/icon/icon-60@3x.png" width="180" height="180"/>
    <icon src="resources/ios/icon/icon-72.png" width="72" height="72"/>
    <icon src="resources/ios/icon/icon-72@2x.png" width="144" height="144"/>
    <icon src="resources/ios/icon/icon-76.png" width="76" height="76"/>
    <icon src="resources/ios/icon/icon-76@2x.png" width="152" height="152"/>
    <icon src="resources/ios/icon/icon-small.png" width="29" height="29"/>
    <icon src="resources/ios/icon/icon-small@2x.png" width="58" height="58"/>
    <icon src="resources/ios/icon/icon-small@3x.png" width="87" height="87"/>
    <icon src="resources/ios/icon/icon.png" width="57" height="57"/>
    <icon src="resources/ios/icon/icon@2x.png" width="114" height="114"/>
    <splash src="resources/ios/splash/Default@2x~iphone.png" width="640" height="960"/>
    <splash src="resources/ios/splash/Default~iphone.png" width="320" height="480"/>
    <splash src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" height="1136"/>
    <splash src="resources/ios/splash/Default-667h.png" width="750" height="1334"/>
    <splash src="resources/ios/splash/Default-736h.png" width="1242" height="2208"/>
    <splash src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" height="1536"/>
    <splash src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" height="768"/>
    <splash src="resources/ios/splash/Default-Landscape-736h.png" width="2208" height="1242"/>
    <splash src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" height="2048"/>
    <splash src="resources/ios/splash/Default-Portrait~ipad.png" width="768" height="1024"/>
  </platform>
  <platform name="android">
    <icon src="resources/android/icon/drawable-ldpi-icon.png" qualifier="ldpi"/>
    <icon src="resources/android/icon/drawable-mdpi-icon.png" qualifier="mdpi"/>
    <icon src="resources/android/icon/drawable-hdpi-icon.png" qualifier="hdpi"/>
    <icon src="resources/android/icon/drawable-xhdpi-icon.png" qualifier="xhdpi"/>
    <icon src="resources/android/icon/drawable-xxhdpi-icon.png" qualifier="xxhdpi"/>
    <icon src="resources/android/icon/drawable-xxxhdpi-icon.png" qualifier="xxxhdpi"/>
  </platform>
</widget>
```

Thanks.

**Comment by aharbick** [comment]
+1

More details here: http://community.phonegap.com/nitobi/topics/cli-6-0-0-not-honoring-target-device-for-ios

**Comment by kerch** [comment]
+1 ...Really need this fixed.  Can't use Phonegap Build unless target-device works

**Comment by beevelop** [comment]
Stumbled upon the same issue. You can track it over here: https://issues.apache.org/jira/browse/CB-10137

As a workaround I used `cordova-custom-config` (https://www.npmjs.com/package/cordova-custom-config) and extended the project's `config.xml` with
```
<platform name="ios">
    <preference name="ios-XCBuildConfiguration-TARGETED_DEVICE_FAMILY" value="1" xcconfigEnforce="true"/>
</platform>
```

This enforces the correct value to target handset devices by overwriting the `build.xcconfig`. @kerch, @aharbick : As I don't use Phonegap Build, I can't guarantee that it will work for you too.

**Comment by dmk2014** [comment]
@beevelop This workaround does not seem to work with Phonegap Build:
```xml
<preference name="phonegap-version" value="cli-6.1.0" />
<plugin name="cordova-custom-config"></plugin>
<platform name="ios">
    <preference name="ios-XCBuildConfiguration-TARGETED_DEVICE_FAMILY" value="1" xcconfigEnforce="true"/>
</platform>
```

The above workaround, however, works perfectly using [Ionic Package](http://docs.ionic.io/docs/package-ios) which currently has the same issue with `target-device`.

**Comment by tsukasa-koizumi** [comment]
I resolve this problem at Cordova 6.0,0.

add,

`TARGETED_DEVICE_FAMILY = 1`

into platforms/ios/cordova/build-release.xcconfig

**Comment by netjets-user** [comment]
I downgraded to 3.9.2 of cordova-ios and then the setting to TARGETED_DEVICE_FAMILY = 1 works as expected.  +1 for getting this fixed for cordova-ios >3.9.2.

**Comment by joevallender** [comment]
Has anyone got a solution for this? I'm using PhoneGap build and not able to build locally using just Cordova at the moment. I tried adding the `<preference name="ios-XCBuildConfiguration-TARGETED_DEVICE_FAMILY" value="1" xcconfigEnforce="true"/>` to the iOS <platform> but no joy. 

I'm trying to get a time sensitive app into the store, and the only thing preventing the approval is a crash on iPad iOS 9. Which is a real pain when it's only for mobile handsets.

Surely this is quite a common feature people require? Lots of apps are intended just for mobile handsets, or the developer doesn't have an iPad to test on etc.

Any advice really appreciated

**Comment by Mahaswami** [comment]
@joevallender  Try to use the cordova-custom-config plugin. Happy to help in case you need further assistance.

**Comment by anibalsanchez** [comment]
+1 Same issue here!

**Comment by wildabeast** [comment]
`target-device` and `deployment-target` preferences should be fixed for iOS now on Build:

    <preference name="target-device" value="handset" />
    <preference name="deployment-target" value="8.0" />

**Comment by joevallender** [comment]
I've just rebuild my dev app and imported to iTunes to check the 'Get Info' and it looks good to me, thanks!

**Comment by anibalsanchez** [comment]
Confirmed!

	<key>UIDeviceFamily</key>
	<array>
		<integer>1</integer>
	</array>

.... however, it still includes Ipad orientations:

	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>

... though it seems to be ignored by iOS and Apple.

**Comment by clemorphy** [comment]
I still have the issue with cordova 6.3.1
I have `<preference name="target-device" value="handset" />` in my config.xml and when I build, I see `TARGETED_DEVICE_FAMILY = 1, 2`

I used @tsukasa-koizumi solution and it worked

**Comment by hemrajdev24000** [comment]
having the same issue on cordova 6.3.1 and <preference name="target-device" value="handset" /> have no effect. Any suggestions?

**Comment by Mahaswami** [comment]
Also same issue in phonegap 6.4.0. Thought this was fixed earlier. It would be great to get some response from Phonegap team as to what is going on here

**Comment by kleeb** [comment]
any updates?

**Comment by kleeb** [comment]
This issue has been fixed in cordova-ios 4.3.1 version: https://issues.apache.org/jira/browse/CB-11243

The latest on Phonegap Build is 4.2.0. I guess we need to wait for the next cli release, which is... ?

**Comment by goya** [comment]
where are you confirming the uidevicefamily in the built ipa? 

i am unable to replicate the issue. as the target-device preference seems to properly flag the proper uidevicefamily in the built ipa.

**Comment by shabal5** [comment]
I'm using DreamWeaver and I can only build for Android.

**Comment by shabal5** [comment]
It's kind of annoying actually. I've done everything I know to do and still can't get phonegap to build for ios.

**Comment by wildabeast** [comment]
@shabal5 https://forums.adobe.com/community/phonegap/build please

**Comment by BenjaminVadant** [comment]
Hi,
It has been some time since the last message on this issue but I'm facing the exact same one using phonegap build cli-8.0.0.
What kind of info do you need to help you debug and fix this?
