### ISSUE TITLE
[build] Valid and unlocked Windows signing key not found when target = uap.

### ISSUE THREAD

**Issue by tonijn** [phonegap/build#529]
Correct key is uploaded and has been unlocked.

```
CertUtil: -importPFX command FAILED: 0x80070002 (WIN32: 2 ERROR_FILE_NOT_FOUND)
CertUtil: The system cannot find the file specified.
my "Personal"
CertUtil: -delstore command completed successfully.
```

This seems to happen at random.
AppId 1026596

cli-6.1.0 (4.1.0 / 5.1.1 / 4.3.1)

**Comment by tonijn** [comment]
Related to #528

**Comment by tonijn** [comment]
This seems to happen only when `windows-apps-target` is set as `uap` but no `windows-arch` is given in the config.xml.

**Comment by ef33zy** [comment]
I get exactly the same error with all my plugins turned off and:

```
<preference name="windows-appx-target" value="uap" />
<preference name='phonegap-version' value='cli-6.3.0'/>
```
`cli-6.3.0 (4.2.0 / 5.2.1 / 4.4.1)`

App ID: 2188160

**Comment by stoffer1** [comment]
I have the same problem as well.

CertUtil: -importPFX command FAILED: 0x80070002 (WIN32: 2 ERROR_FILE_NOT_FOUND)
CertUtil: The system cannot find the file specified.
my "Personal"
CertUtil: -delstore command completed successfully.

**Comment by wildabeast** [comment]
This was an ongoing issue that should now be fixed.

**Comment by stoffer1** [comment]
Still got the same problem this morning - app id 1344550

From the error log:

CertUtil: -importPFX command FAILED: 0x80070002 (WIN32: 2 ERROR_FILE_NOT_FOUND)
CertUtil: The system cannot find the file specified.
My "Personal"
CertUtil: -delstore command completed successfully.

**Comment by sabrielle6** [comment]
i get EXACTLY the same error. does anyone have any fixes?

**Comment by wildabeast** [comment]
Please try building again now.

**Comment by sabrielle6** [comment]
Holy moly, that time it worked. what was fixed?

**Comment by stoffer1** [comment]
Mine is still broken

**Comment by frederikbosch** [comment]
```
Installing "phonegap-plugin-push" at "1.8.1" for windows
CertUtil: -importPFX command FAILED: 0x80070002 (WIN32: 2 ERROR_FILE_NOT_FOUND)
CertUtil: The system cannot find the file specified.
My "Personal"
CertUtil: -delstore command completed successfully.
```

Maybe it is linked to `phonegap-plugin-push`?

**Comment by frederikbosch** [comment]
It is not, removing all plugins also has the error.

**Comment by frederikbosch** [comment]
Maybe @wildabeast can give a clue what causes the error, maybe there is a workaround.

**Comment by frederikbosch** [comment]
Okay, I have tried at least 20 builds. I even build a retry script so that I don't have to try manually. It just won't work.

**Comment by apetrichkovich** [comment]
Have the same problem.
My last zip-file doesn't have config.xml and resources (no one plugin is there).
Only index.html, css, js.

Build Date: 2016-10-14 15:15:56 +0000
================ Certificate 0 ================
================ Begin Nesting Level 1 ================
Element 0:
Serial Number: 587c315f16f24a9c44be739c9b490957
Issuer: CN=Tildepost
 NotBefore: 10/14/2016 3:02 PM
 NotAfter: 12/31/2039 11:59 PM
Subject: CN=Tildepost
Signature matches Public Key
Root Certificate: Subject matches Issuer
Cert Hash(sha1): b7 20 10 a5 9b be f5 02 64 d3 34 77 2f cf 7d f0 c3 30 79 2d
----------------  End Nesting Level 1  ----------------
  Provider = Microsoft Strong Cryptographic Provider
Signature test passed
CertUtil: -dump command completed successfully.
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
CertUtil: -importPFX command FAILED: 0x80070002 (WIN32: 2 ERROR_FILE_NOT_FOUND)
CertUtil: The system cannot find the file specified.
My "Personal"
CertUtil: -delstore command completed successfully.

**Comment by wildabeast** [comment]
Should be fixed now, please rebuild

**Comment by frederikbosch** [comment]
@wildabeast Thanks for your work!

**Comment by vereslabs** [comment]
Same error. Can you check please? I've tried many different settings, a plain, low-case, no spaces pfx file, but still no success building the windows version:

Build Date: 2017-01-04 14:59:08 +0000
================ Begin Nesting Level 1 ================
................
Signature matches Public Key
Root Certificate: Subject matches Issuer
Cert Hash(sha1): a1 09 fb 9a 0b 90 3f 55 5c 44 b7 8f 6a 24 c4 35 bf 0c f7 f1
----------------  End Nesting Level 1  ----------------
  Provider = Microsoft Strong Cryptographic Provider
Signature test passed
CertUtil: -dump command completed successfully.
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-console@~1.0.2" via npm
Installing "cordova-plugin-console" at "1.0.5" for windows
Fetching plugin "cordova-plugin-whitelist@~1.2.1" via npm
Installing "cordova-plugin-whitelist" at "1.2.2" for windows
CertUtil: -importPFX command FAILED: 0x80070002 (WIN32: 2 ERROR_FILE_NOT_FOUND)
CertUtil: The system cannot find the file specified.
My "Personal"
CertUtil: -delstore command completed successfully.

**Comment by TriSysBusinessSoftware** [comment]
Its May 2017 and this problem is still there.

**Comment by jarmediagmbh** [comment]
Problem still exists in July. It is a shame that support is so bad for a paid service.

**Comment by jgwcouk** [comment]
Same problem here - is anyone listening?

**Comment by goya** [comment]
this is an issue with windows and is intermittent, random and annoying. we are struggling to find the cause and fix it.

**Comment by jarmediagmbh** [comment]
Hi goya. It does not seem to be that random, as the error constantly shows up for over a week now. We have an automation script which collects statistics and which is not able to rebuild signed windows apps since then. It retires nearly every minute. Is there anything we can help you with to get this fixed?

**Comment by goya** [comment]
what appid is failing?  i see you have one app signing properly.

**Comment by jarmediagmbh** [comment]
Thank's goya, whatever you did - it solved the issue for us. The app has been successfully build yesterday evening - at 7:29 PM GMT+1. We will tell you here if the issue occurs again.

**Comment by goodfellasthai** [comment]
I am getting exactly the same error - it actually worked once but then a new build has started failing again.

My appid is 2515079 someone help me pleeasssee :)

**Comment by jarmediagmbh** [comment]
It is not working for us again. Also yesterday we had a couple of errors but retrying solved it for us. Our App-ID is 2313940

**Comment by goodfellasthai** [comment]
Hi I am not sure if anyone did anything but now I can successfully build my appx file now - one thing I have noticed is that previously it looked like it was trying to build it x86 I assume 32-bit the succesful build has built 64-bit

**Comment by orenagiv** [comment]
Not sure if it's the actual solution, but for me, if I used the Publisher ID as the Common Name of the certificate, it worked (but only in the second time I tried to compile...)

![windows](https://user-images.githubusercontent.com/2144775/29072679-52f11298-7c51-11e7-921d-13b0db81f906.png)

Also, I have the following preferences in my config.xml:

<preference name="windows-arch" value="x64" />
<preference name="windows-identity-name" value="xxxxxxxx.yyyyyyyyyyy" />
<preference name="windows-appx-target" value="uap" />

Note: The "xxxxxxxx.yyyyyyyyyyy" is the exact value of the identity attribute from the attached image.

**Comment by UTHINKUKNOWME** [comment]
@orenagiv Can you please provide me with the steps on how did u created the certificate exactly? Thank you

**Comment by AndrePinto-NET** [comment]
Have the same issue here! Is this not solved yet? 

--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
CertUtil: -importPFX command FAILED: 0x80070002 (WIN32: 2 ERROR_FILE_NOT_FOUND)
CertUtil: The system cannot find the file specified.
My "Personal"
CertUtil: -delstore command completed successfully.
