### ISSUE TITLE
Android problem on compile in PGBuild

### ISSUE THREAD

**Issue by asalgueiro** [phonegap/build#638]
Hi,

This is reported in Forum in multiple threads:

https://forums.adobe.com/thread/2551566
https://forums.adobe.com/thread/2500401
https://forums.adobe.com/thread/2551918

Since 22nd oct, some plugins breaked when try to get a .jar file from jcenter repository. 

This issue can be solved editing gradle script to alter the repositories order but PGB users can't change that.

Will be a fix available soon? 
Thanks

**Comment by goya** [comment]
there hasn’t been any provisioning changes on build for a while.

investigating now.

**Comment by goya** [comment]
do you have a sample app or app id # that can reproduce this? or what plugins cause this error?

**Comment by asalgueiro** [comment]
App ID: 1006158
Plugin affected: phonegap-plugin-push

Some others have problems with plugin cordova-plugin-multidex and cordova-plugin-googleplus

Thanks!

**Comment by Burfelt** [comment]
This sample app will fail right now:

https://github.com/jcesarmobile/phonegap-plugin-push-sample

**Comment by infuzz** [comment]
same for me : 
Could not find multidex.jar (com.android.support:multidex:1.0.2).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/multidex/1.0.2/multidex-1.0.2.jar

-----------------------------------------------------------------------------------------------
Maybe build.gradle on PGB should be modified to let maven in first place rather than jcenter like this : 
  repositories {
        maven {
            url "https://maven.google.com"
        }
        jcenter()
    }

 [See this](https://ionic.zendesk.com/hc/en-us/articles/360005529314-Android-builds-fail-due-to-missing-jcenter-dependencies)

**Comment by goya** [comment]
this should be fixed on prod. 

very annoying problem to come out of the blue.

**Comment by infuzz** [comment]
I can confirm that I can compile right now !

pgb uses maven repositories rather than jcenter.

Great works ! thx pgb team, thx you Goya !

**Comment by Burfelt** [comment]
Confirmed that I can compile too!

Thanks for moving on this,

**Comment by goya** [comment]
i have been unable to find a smoking gun.  if anyone has the changelog of a gradle change or script update that caused this, i would be ever so grateful.

**Comment by juankza95** [comment]
I'm still experiencing this issue, and seems like I'm not the only too (https://forums.adobe.com/message/10707946#10707946).

I also opened a thread, https://forums.adobe.com/thread/2552826 .

Any tip?
